# Generated by Django 3.1.4 on 2020-12-25 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0002_projectdetails_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='users',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='userdata',
            field=models.ManyToManyField(blank=True, related_name='userdata', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
