# Generated by Django 3.1.4 on 2020-12-26 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0003_auto_20201225_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='userdata',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
